version: '3'
services:
  web:
    build: 
      context: ./backend
      dockerfile: backend.development.dockerfile
    volumes:
      - ./backend:/backend
    environment:
      - PORT=3030
    ports:
      - "3030:3030"
    expose:
      - 3030

  database:
    restart: unless-stopped
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5430:5432"
    expose:
      - 5430
    volumes:
      - ./db:/var/lib/postgresql/data